### ISSUE TITLE
Ensure OpenSim API works via MATLAB

### ISSUE THREAD

**Issue by adamkewley** [ComputationalBiomechanicsLab/systems#26]
For @itbellix 

It might be that it's already set up. Otherwise, OpenSim needs to be built from source against the MATLAB API.

IIRC there might be some annoying issues with doing this, though (last time I tried, it segfaulted for no reason, etc.)

**Comment by itbellix** [comment]
Hi @adamkewley, thank you!
Do I need to be granted any permissions to acces the machine? Also, I recall seeing some instructions on how to use it, but maybe can you point me to the correct ones to follow?

**Comment by adamkewley** [comment]
I have confirmed that the MATLAB that's installed on the system does appear to have OpenSim installed.

@itbellix , for the instructions, you are posting on the repository that contains them. See README:

https://github.com/ComputationalBiomechanicsLab/systems

Notably, you'll want to VNC onto a desktop, boot MATLAB, and ensure you can use the OpenSim API. VNC clients like RealVNC etc. have a feature for copying files to-and-from the computer. You can also use programs like WinSCP, or Window's in-built command line (e.g. `scp`) to copy things around.
