### ISSUE TITLE
Fix punitha crash

### ISSUE THREAD

**Issue by adamkewley** [ComputationalBiomechanicsLab/systems#36]
Punitha reported a crash after running her conda pipeline via VNC. Here's some notes I took while fixing it

- VNC is up, but shows `unable to contact settings server` after restarting
- The internet says that booting `dbus` explicitly might be necessary: https://forum.xfce.org/viewtopic.php?id=15896
- Tried adding this to `/home/punitha/.vnc/xstartup`, seemed to have no effect
- `punitha` was missing an `.Xresources` file, re-added it (it's blank on my account, so I'm assuming it isn't important?) - no effect
- Removed `PYTHONPATH` setter before running `startxfce4` - **FIXED**

I'm assuming that the issue is that `startxfce` or some part of the session init process is using `python`, and that it imports modules from (what it believes to be) the base OS, but the `PYTHONPATH` override was causing it to pull from `/usr/local/lib`, which might've provided a conflicting version of some module? Unsure, requires more investigation. However, it's working for now and will be bounced back to punitha for verification.

**Comment by punithad** [comment]
Hi Adam,

I checked. I still have black screen when i open VNC viewer. 
Running the files in terminal is going good. 

But I am not able to view them in VNC viewer. (I uninstalled and reinstalled it)

Can you please help me?

**Comment by adamkewley** [comment]
The issue in this case appears to be that there was multiple VNC servers running for the account. May have been that the one I booted was treated separately.

I have reset the VNC server for yours + my account. The only one running on the server right now is Samane's. This can be verified with `ps aux | grep Xtiger`.

To get one working, you'll need to set the password and boot it for your account: `cbl_vnc-passwd ; cbl_vnc-start`.

**Comment by punithad** [comment]
its working now. 

Thank you, Adam.
